### PR TITLE
Add version task

### PR DESCRIPTION
**Pull request by shadowfacts**
You placed the version task in the `buildscript` block of the `build.gradle` file. You needed to place it at the top level.

### CODE REVIEW

**Comment by LordMastodon** [comment]
Github is telling me your branch has conflicts, not letting me merge the branches. It's probably because I did a few pushes after you forked it, try forking it again and then making the changes.

**Comment by shadowfacts** [comment]
You can follow [these](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/) instructions to resolve the conflicts.

**Comment by LordMastodon** [comment]
Pretty sure I royally screwed this up. Pushing from SourceTree seems to have pushed to your branch for some reason, and then a look at your branch tells me it hasn't... I'll close your pull request now that I've got your edit to stop any further confusion.

**Comment by LordMastodon** [comment]
Not even sure what's happening. SourceTree tells me it's pushing to my branch and then it doesn't push at all. Also, build of your branch seems to have failed as well: Execution failed for task ':deobfMcMCP'.
 Your Access Transformers be broke!

**Pull request closed without merging**
